version: '3'
services:
  webapp:
    container_name: museum-admin-pwa
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8090:3000

networks:
  default:
    external: true
    name: spring-cloud-network